version: "3.9"

services:
  # Service for the API
  api:
    image: todo-api # Docker image for the API service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./src/migrations:/app/src/migrations
    env_file:
      - .env # Loads environment variables from the .env file
    depends_on:
      - db
    command: >
      sh -c "npm run build &&
             npm run migration:run &&
             npm run start"
    ports:
      - "5000:5000" # Maps port 5000 on the host to port 5000 in the container
    restart: always

  # Service for the PostgreSQL database
  db:
    image: postgres:17
    ports:
      - "5432:5432" # Maps port 5432 on the host to port 5432 in the container
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"] # Checks if PostgreSQL is ready to accept connections
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

